version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: '${POSTGRESS_DB_NAME}'
      POSTGRES_USER: '${POSTGRESS_USER}'
      POSTGRES_PASSWORD: '${POSTGRESS_PASS}'
    ports:
      - '5432:${POSTGRESS_PORT}'
    restart: always
